messenger/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "messenger"

urlpatterns = [
    path('detail_m/<str:id>', detail_m, name = "detail_m"),
    path('new_m/', new_m, name = "new_m"),
    path('send_m/', send_m, name = "send_m"),
    path('received_m/', receive_m, name = "received_m"),
    path('delete_m/<str:id>', delete_m, name = "delete_m"),
    path('new/<str:receiver>', new_static, name="new_static")
]

muse/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from review.views import index

urlpatterns = [
    path('', index, name="index"),
    path('admin/', admin.site.urls),
    path('review/', include('review.urls')),
    path('ticket/', include('ticket.urls')),
    path('messenger/', include('messenger.urls')),
    path('accounts/', include('allauth.urls')),
    path('user/', include('user.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "ticket"

urlpatterns = [
    path('', ticket, name="ticket"),
    path('<int:id>', detail, name="ticket_detail"),
    path('new/', new, name="ticket_new"),
    path('edit/<int:id>', edit, name="ticket_edit"),
    path('delete/<int:id>', delete, name="ticket_delete"),
    path('search', search, name = 'search'),
]

ticket/models.py
from django.db import models
from django.contrib.auth import get_user_model
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

# Create your models here.

class Ticket(models.Model):
    ticket = models.CharField(max_length=200)
    writer = models.CharField(max_length=100)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='author', null=True)
    date = models.DateTimeField()
    contents = models.TextField()
    image = models.ImageField(upload_to='ticket/', blank=True, null=True)
    image_thumbnail = ImageSpecField(source = 'image', processors = [ResizeToFill(250, 230)])

    def __str__(self):
        return self.ticket    
    
    def summary(self):
        return self.contents[:30]

ticket/forms.py
from django import forms
from .models import Ticket

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['ticket','contents','image']

        widgets = {
            'contents': forms.Textarea(
            attrs={'placeholder': '티켓은 원가 양도만 가능합니다. 원가 양도를 제외한 양도는 불법입니다.'}),
        }

ticket/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.core.paginator import Paginator
from django.db.models import Q
from .models import Ticket
from .forms import TicketForm

# Create your views here.

def ticket(request):
    contents = Ticket.objects.all()
    ticket_list = Ticket.objects.all().order_by('-id')
    paginator = Paginator(ticket_list, 3)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    return render(request, 'ticket_home.html', {'contents': contents, 'posts':posts})


def detail(request, id):
    data = get_object_or_404(Ticket, pk = id)
    return render(request, 'ticket_detail.html', {'data':data})

def new(request):
    if request.method == 'POST':
        ticket_form = TicketForm(request.POST, request.FILES)
        if ticket_form.is_valid():
            ticket = ticket_form.save(commit=False)
            ticket.date = timezone.now() #날짜 생성
            ticket.author = request.user
            ticket.save()
            return redirect('ticket:ticket')
    else:
        ticket_form = TicketForm()
        return render(request, 'ticket_new.html', {'form':ticket_form})

def edit(request, id):
    post = get_object_or_404(Ticket, pk = id)
    if request.method == 'GET':
        ticket_form = TicketForm(instance = post)
        return render(request, 'ticket_edit.html', {'edit_ticket' : ticket_form, 'ticket' : post})
    else:
        ticket_form = TicketForm(request.POST, request.FILES, instance = post)
        if ticket_form.is_valid():
            ticket = ticket_form.save(commit=False)
            ticket.date = timezone.now() 
            ticket.save()
        return redirect('ticket:ticket_detail', ticket.id)

def delete(request, id):
    erase_ticket = Ticket.objects.get(id = id)
    if request.user == erase_ticket.author:
        erase_ticket.delete()
    return redirect('ticket:ticket')

def messenger(request, id):
    post = get_object_or_404(Ticket, pk = id)
    if request.method == 'GET':
        ticket_form = TicketForm(instance = post)
        return render(request, 'ticket_edit.html', {'edit_ticket' : ticket_form})
    else:
        ticket_form = TicketForm(request.POST, request.FILES, instance = post)
        if ticket_form.is_valid():
            ticket = ticket_form.save(commit=False)
            ticket.date = timezone.now() 
            ticket.save()
        return redirect('ticket:ticket_detail', ticket.id)

def search(request):
    tickets = Ticket.objects.all().order_by('-id')
    q = request.POST.get('q', "") 

    if q:
        tickets = tickets.filter(ticket__icontains=q) | tickets.filter(contents__icontains=q)
        return render(request, 'search.html', {'tickets' : tickets, 'q' : q})
    else:
        return render(request, 'search.html')

ticket/templates/search.html
{% extends 'base.html' %}

{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/bootstrap.css">
    <script src="js/jquery-3.1.1.js"></script>
    <script src="js/bootstrap.js"></script>
    <Style>
        .allreview-box a{
            color: black;
            background-color: #F1EB73;
            padding: 5px;
            margin: 10px;
            text-decoration:none;
        }
        .allreview-box a:hover{
            text-decoration: underline;
        }
        .ticket-table{
            background-color: rgb(255, 255, 240);
            margin: 20px;
        }
        .table a{
            color: black;
            text-decoration: none;
        }
        .table a:hover {
            text-decoration: underline;
        }
        .green-active:hover{
            background-color: rgba(198, 247, 183, 0.685);
        }
    </style>
</head>
    <h1>검색 결과</h1>
    {% if not tickets %}
        <br>
        <h1>검색 결과가 없습니다.</h1>
    {% else %}

        <!-- {% for data in tickets.all %}
        <div class="container">
            <div class="card">
                <div class="card text-white bg-success">
                    <h1>{{ data.ticket }}</h1>
                    <p>{{ data.date | date:"Y-m-d" }}</p>
                    <p>{{ data.summary }}
                    <br>
                    <div class="allreview-box">
                        <a href="{% url 'ticket:ticket_detail' data.id %}"> ...더 보기</a></p> 
                    </div>
                </div>
            </div>
        </div>
        <br>
        {% endfor %} -->


        <div class="ticket-table">
            <table class="table table-bordered">
                <tr>
                    <td>뮤지컬</td>
                    <td>글 내용</td>
                    <td>작성자</td>
                    <td>작성일</td>
                </tr>
                {% for content in tickets %}
                <tr class="green-active">
                    <td>{{content.ticket}}</td>
                    <td><a href="{% url 'ticket:ticket_detail' content.id %}">{{content.summary}}...</a></td>
                    <td>{{content.author}}</td>
                    <td>{{content.date | date:"Y-m-d"}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>

    {% endif %}

{% endblock %}

ticket/templates/ticket_detail.html
{% extends 'base.html' %}
{% block content %}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <Style>
        body {
            font-family: 'Alfa Slab One', 'Do Hyeon';
            color: white;
        }
        hr {
            color: black;
            border: 30px;
        }
        #data {
            border-radius: 15px;
            background-color: #F1EB73;
            color: rgb(48, 48, 48);
        }
        .etc {
            color: rgb(187, 187, 187);
        }
        .allreview-box a{
            color: black;
            background-color: #F1EB73;
            padding: 5px;
            margin: 10px;
            text-decoration:none;
        }
        .allreview-box a:hover{
            text-decoration: underline;
        }
        .detail-box {
            min-height: 300px;
            background-color: rgb(255, 255, 240);
            color: black;
            text-align: left;
            padding: 10px;
            margin: 10px auto;
        }
        #id_date{
            float: right;
        }
        .ticket-div{
            margin-top: 10px;
            margin-bottom: 10px;
            background-color: rgba(113, 203, 255, 0.541);
        }
    </Style>
</head>

<body>

    <div class="detail-box">
        <div>
            <span>&#128100;&nbsp;작성자 : {{data.author}}</span>
            <span id="id_date">{{data.date}}</span>
        </div>
        <div class="ticket-div"><span>&#127915;&nbsp;양도 티켓 : {{data.ticket}}</span></div>
        <a href="{%url 'messenger:new_static' data.author %}" class="btn-yellow">&#9993;&nbsp;{{data.author}}에게 쪽지보내기</a>
        <hr>
        <p>{{data.contents | linebreaks}}</p>
        {% if data.image %}
            <p><img src="{{data.image.url}}" alt="" width="60%" height=""></p>
        {% endif %}
    </div>


    <!-- <h1>{{data.ticket}}</h1>

    <div id="info">
       {{data.date}}
    </div>
    
    <div class="body">
        <div id="data"> by. {{data.author}}<br><br>
            {{data.contents | linebreaks}}
          
        {% if data.image %}
            <p><img src="{{data.image.url}}" alt="" width="60%" height=""></p>
        {% endif %}
        </div>  
    </div> -->

    {% if request.user == data.author %}
    <div class="etc">
        <div class="allreview-box">
        <a href="{% url 'ticket:ticket_edit' data.id %}"><span style="color:rgb(119, 119, 119);">▶Edit </span></a>
        <a href="{% url 'ticket:ticket_delete' data.id %}"><span style="color:rgb(119, 119, 119);">▶Delete</span></a> 
        </div> 
    </div>
    {% endif %}
    
    <hr> 
    {% comment %} 티켓 양도 댓글을 위한 공간... {% endcomment %}

</body>
{% endblock %}

ticket/templates/ticket_edit.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <Style>
        .body {
            text-align: center;
        }
        /* input,
        textarea {
            font-family: 'Do Hyeon', sans-serif;
            width: 50%;
            border: none;
            background-color: #F1EB73;
            border-radius: 20px;
            padding: 10px;
            margin: 0px 50px;
            font-size: 18px;
            color: black;
        }
        h2{
            color:white;
            font-family: 'Do Hyeon', sans-serif;
            text-align: right;
            margin-top:30px;
            margin-right: 25%;
            
        } */
        .controls {
            color: black;
            overflow: hidden;
        }
        #id_contents, #id_ticket, #id_image {
            background-color: #fffba8;
            border: none;
            border-radius: 20px;
            padding: 10px;
        }
        #submit_btn{
            width: 60px;
            padding: 5px;
            margin: 10px;
        }
        .controls a {
            color: rgb(3, 0, 202);
        }
    </Style>
</head>

{% if request.user == ticket.author %}
<h1>글 수정</h1>
<form method="POST" id="update_form" enctype="multipart/form-data">
    {%csrf_token%}
    {{edit_ticket | crispy}}
    <button id="submit_btn" type="submit">확인</button>
</form>
{% else %}

<h3>이 경로로 들어오다니 나쁜 사람.. <br>당신은 글쓴이가 아닙니다. 나가세요.</h3>
{% endif %}
{% endblock %}

ticket/templates/ticket_home.html
{% extends 'base.html' %}
{% block content %}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/bootstrap.css">
    <script src="js/jquery-3.1.1.js"></script>
    <script src="js/bootstrap.js"></script>
    <Style>
        .footer {
            position: static;
            left: 0;
            bottom: 0;
            width: 100%;
            padding: 15px 0;
            text-align: center;
            color: black;
            background: #F1EB73;
        }
        h2,h5,p,small{
            color: black;
        }
        .card-deck {
            background: #F1EB73;
        }
        .allticket-box a{
            color: black;
            background-color: #F1EB73;
            padding: 5px;
            margin: 10px;
            text-decoration:none;
        }
        .allticket-box a:hover{
            text-decoration: underline;
        }
        .allticket-box {
            margin: 10px;
            height: 30px;
        }
        .ticket-table{
            background-color: rgb(255, 255, 240);
        }
        .table a{
            color: black;
            text-decoration: none;
        }
        .table a:hover {
            text-decoration: underline;
        }
        .green-active:hover{
            background-color: rgba(198, 247, 183, 0.685);
        }
    </Style>
</head>

    <h1>티켓 양도 게시판</h1>
    
    <div class="allticket-box">
        <a href="{% url 'ticket:ticket_new' %}" id="go_new">티켓 양도 글쓰기</a>
    </div>
    
    <div class="ticket-table">
        <table class="table">
            <tr>
                <td>뮤지컬</td>
                <td>글 내용</td>
                <td>작성자</td>
                <td>작성일</td>
            </tr>
            {% for content in posts %}
            <tr class="green-active">
                <td>{{content.ticket}}</td>
                <td><a href="{% url 'ticket:ticket_detail' content.id %}">{{content.summary}}...</a></td>
                <td>{{content.author}}</td>
                <td>{{content.date | date:"Y-m-d"}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>


    <!-- <div class="container">
        <div class="card-deck mb-3 text-center"> 
            {% for content in posts %}
            <div class="card mb-3 shadow-sm">   
            <div class="card-header">
                <h2>{{content.ticket}}</h2>
            </div>    
            
            <div class="card-body">
                {% if content.image %}
                    <p class = "image"><img src="{{content.image_thumbnail.url}}" height="200" width="400"></p>
                {% endif %}
                
                
                <h5 class="card-title"><b>{{content.ticket}}</b></h5>
                <br>
                <small class="card-title">by. {{content.author}}</small><br>
                <p class="card-text"></p>{{content.summary | linebreaks}}</p>

                <div class="allreview-box">
                <a href="{% url 'ticket:ticket_detail' content.id %}" id="more">자세히보기</a>
                </div>

            </div>
            {% endfor %}
        </div>
    </div> -->

    <div class="footer">
        {% if posts.has_previous %}
            <a href="?page=1">1</a>
            <a href="?page={{posts.previous_page_number}}">◀</a>
        {% endif %}
        <span>{{posts.number}}</span>
        <span>of</span>
        <span>{{posts.paginator.num_pages}}</span>
        {%if posts.has_next%}
            <a href="?page={{posts.next_page_number}}">▶</a>
            <a href="?page={{posts.paginator.num_pages}}">{{posts.paginator.num_pages}}</a>
        {% endif %}
    </div>

{% endblock %}

ticket/templates/ticket_new.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <Style>
        .body {
            text-align: center;
        }
        h2{
            color:white;
            font-family: 'Do Hyeon', sans-serif;
            text-align: right;
            margin-top:30px;
            margin-right: 25%;
        }
        .controls {
            color: black;
        }
        #id_contents, #id_ticket, #id_image {
            background-color: #fffba8;
            border: none;
            border-radius: 20px;
            padding: 10px;
        }
        #submit_btn{
            width: 60px;
            padding: 5px;
            margin: 10px;
        }
    </Style>
</head>

<body>
    {% if user.is_authenticated %}
    <h1>글 작성</h1>
    <form id="write_form" action="{% url 'ticket:ticket_new' %}" method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        {{form | crispy}}
        <button id="submit_btn" type="submit">확인</button>
    </form>
    {% else %}

    <h4>로그인 후 이용하세요<br>
    <a href="{% url 'account_login' %}">로그인</a>
    </h4>
    {% endif %}
</body>
{% endblock %}