messenger/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "messenger"

urlpatterns = [
    path('detail_m/<str:id>', detail_m, name = "detail_m"),
    path('new_m/', new_m, name = "new_m"),
    path('send_m/', send_m, name = "send_m"),
    path('received_m/', receive_m, name = "received_m"),
    path('delete_m/<str:id>', delete_m, name = "delete_m"),
    path('new/<str:receiver>', new_static, name="new_static")
]

muse/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from review.views import index

urlpatterns = [
    path('', index, name="index"),
    path('admin/', admin.site.urls),
    path('review/', include('review.urls')),
    path('ticket/', include('ticket.urls')),
    path('messenger/', include('messenger.urls')),
    path('accounts/', include('allauth.urls')),
    path('user/', include('user.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "review"

urlpatterns = [
    path('detail/<str:id>', detail, name='detail'),
    path('new/<str:mt20id>', new, name='new'),
    path('allreviews', allReviews, name="allreviews"),
    path('', index, name='index'),
    path('search/', showSearch, name="search"),
    path('delete/<str:id>/<str:mt20id>', delete, name="delete"),
]

ticket/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "ticket"

urlpatterns = [
    path('', ticket, name="ticket"),
    path('<int:id>', detail, name="ticket_detail"),
    path('new/', new, name="ticket_new"),
    path('edit/<int:id>', edit, name="ticket_edit"),
    path('delete/<int:id>', delete, name="ticket_delete"),
    path('search', search, name = 'search'),
]

user/urls.py
from django.urls import path
from .views import *

app_name = "user"

urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('profile/update/', profile_update_view, name='profile_update'),
    path('delete', profile_delete, name='profile_delete'),
]

muse/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MUSE</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
    body {
        text-align: center;
        font-weight: 400;
        background: #006F3E;
        color: white;
        height: 100%;
        padding: 0px;
        margin: 0px;
        font-family: 'Do Hyeon', sans-serif;
    }
    #logo {
      width: 60px;
      height: 60px;
    }
</style>

</head>
<body>
  {% load static %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{%url 'review:index' %}"><img src="{%static 'whiteback-logo.png' %}" id="logo"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'review:index' %}">뮤지컬 후기</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ticket:ticket' %}">티켓 양도</a>
          </li>
          

          <!-- <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li> -->
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              쪽지함
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'messenger:received_m' %}">받은 쪽지</a></li>
              <li><a class="dropdown-item" href="{% url 'messenger:send_m' %}">보낸 쪽지</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'messenger:new_m' %}">쪽지 보내기</a></li>
            </ul>
          </li>
          {% endif %}
          <!-- <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li> -->
        </ul>

        <span class="navbar-text">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{user.nickname}}님
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
          </ul>
        </li>
        {% endif %}
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'account_login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'account_signup' %}">SignUp&nbsp;&nbsp;</a>
        </li>
        {% endif %}
        </ul>
        </span>
        
        <form class="d-flex" action="{% url 'ticket:search' %}" method="post">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="티켓 양도 게시판 검색" aria-label="Search" name="q" value="{{q}}">
        <button class="btn btn-outline-success" type="submit">검색</button>
      </form>
      </div>
    </div>
  </nav>
  <div class = "container">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>