muse/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from review.views import index

urlpatterns = [
    path('', index, name="index"),
    path('admin/', admin.site.urls),
    path('review/', include('review.urls')),
    path('ticket/', include('ticket.urls')),
    path('messenger/', include('messenger.urls')),
    path('accounts/', include('allauth.urls')),
    path('user/', include('user.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "review"

urlpatterns = [
    path('detail/<str:id>', detail, name='detail'),
    path('new/<str:mt20id>', new, name='new'),
    path('allreviews', allReviews, name="allreviews"),
    path('', index, name='index'),
    path('search/', showSearch, name="search"),
    path('delete/<str:id>/<str:mt20id>', delete, name="delete"),
]

review/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models.deletion import CASCADE
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

# Create your models here.

class Review(models.Model):
  mt20id = models.CharField(max_length=10)
  title = models.CharField(max_length=50)
  author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='reviewers')
  rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])
  upload_date = models.DateTimeField()
  view_date = models.DateField()
  view_time = models.TimeField()
  cast1 = models.CharField(max_length=10, blank=True, null=True)
  cast2 = models.CharField(max_length=10, blank=True, null=True)
  body = models.TextField()
  image = models.ImageField(upload_to='review/%Y/%m/%d/', null=True, blank=True)
  image_thumbnail = ImageSpecField(source='image', processors=[ResizeToFill(200, 200)])

  def __str__(self):
    return self.mt20id

  class Meta:
    ordering = ['-upload_date']


# class SortCondition(models.Model):
#   TITLE_CHOICES = list(Review.objects.values_list('title', 'title').order_by('title').distinct())
#   cast1_list = list(Review.objects.values_list('cast1', 'cast1').order_by('cast1').distinct().exclude(cast1__isnull=True).exclude(cast1__exact='')) 
#   cast2_list = list(Review.objects.values_list('cast2', 'cast2').order_by('cast2').distinct().exclude(cast2__isnull=True).exclude(cast2__exact=''))
#   DATE_CHOICES = list(Review.objects.values_list('view_date', 'view_date').order_by('view_date').distinct())
#   CAST_CHOICES = cast1_list + cast2_list
#   TIME_CHOICES = list(Review.objects.values_list('view_time', 'view_time').order_by('view_time').distinct())

#   title = models.CharField(max_length=50,choices=TITLE_CHOICES, blank=True)
#   cast = models.CharField(max_length=10, choices=CAST_CHOICES, blank=True)
#   view_date = models.DateField(choices=DATE_CHOICES, blank=True)
#   view_time = models.TimeField(choices=TIME_CHOICES, blank=True)

#   title2 = models.ForeignKey(Review, on_delete=CASCADE, blank=True)




# class ShowDetail(models.Model):
#   mt20id = models.CharField(max_length=20)
#   datefrom = models.CharField(max_length=10)
#   dateto = models.CharField(max_length=10)
#   facility = models.CharField(max_length=200)
#   poster = models.TextField()
#   genre = models.CharField(max_length=20)
#   state = models.CharField(max_length=20)
#   cast	= models.CharField(max_length=200)
#   crew	= models.CharField(max_length=50)
#   runtime	= models.CharField(max_length=20)
#   agelimit = models.CharField(max_length=50)
#   enterprise = models.CharField(max_length=50)
#   price = models.CharField(max_length=200)
#   story	= models.TextField()	
#   dateguidance = models.TextField()

review/forms.py
from django import forms
from django.forms import Form, CharField, TextInput, PasswordInput, ChoiceField, BooleanField
from django.forms import widgets
from django.forms.fields import DateField, DateTimeField, ImageField, IntegerField, SplitDateTimeField, TimeField
from django.forms.widgets import DateTimeInput, NumberInput, Textarea
from django.utils.regex_helper import Choice
from .models import Review


class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class NewReviewForm(forms.ModelForm):
    rating = IntegerField(
        widget = NumberInput(attrs = { 'max':10, 'step':1, 'min':0 }),
        label='만족도'
    )
    view_date = DateField( 
        widget = DateInput(),
        label='관람일'
    )
    view_time = TimeField(
        widget = TimeInput(),
        label='관람시간'
    )
    cast1 = CharField(
        widget = TextInput( attrs={'placeholder': '배우명'}),
        label='출연 배우(1)'
    )
    cast2 = CharField(
        widget = TextInput( attrs={'placeholder': '배우명'}),
        required=False,
        label='출연 배우(2)'
    )
    body = CharField(
        widget = Textarea(attrs={'placeholder': '후기를 작성해주세요'}),
        label = "후기"
    )
    image = ImageField(required=False, label='사진 첨부')
    class Meta:
        model = Review
        fields = ['rating', 'view_date','view_time', 'cast1', 'cast2', 'body', 'image']


# class SortReviewForm(forms.ModelForm):
#     SortCondition.TITLE_CHOICES.insert(0, ('', '---------'))
#     SortCondition.CAST_CHOICES.insert(0, ('', '---------'))
#     SortCondition.DATE_CHOICES.insert(0, ('', '---------'))
#     SortCondition.TIME_CHOICES.insert(0, ('', '---------'))
#     title = ChoiceField(label="공연명", choices=SortCondition.TITLE_CHOICES, required=False)
#     cast = ChoiceField(label="배우", choices=SortCondition.CAST_CHOICES, required=False)
#     view_date = ChoiceField(label="관람일", choices=SortCondition.DATE_CHOICES, required=False)
#     view_time = ChoiceField(label="관람시간", choices=SortCondition.TIME_CHOICES, required=False)
#     class Meta:
#         model = SortCondition
#         fields = ['title', 'title2', 'cast', 'view_date', 'view_time']


# class SortSmallForm(forms.ModelForm):
#     cast = ChoiceField(label="배우", choices=SortCondition.CAST_CHOICES, required=False)
#     view_date = ChoiceField(label="관람일", choices=SortCondition.DATE_CHOICES, required=False)
#     view_time = ChoiceField(label="관람시간", choices=SortCondition.TIME_CHOICES, required=False)
#     class Meta:
#         model = SortCondition
#         fields = [ 'cast', 'view_date', 'view_time']


class ReviewSortForm(Form):
    cast = CharField(
        widget = TextInput( attrs={'placeholder': '배우 이름'}),
        label='배우',
        required=False
    )
    view_date = DateField( 
        widget = DateInput(),
        label='관람일', 
        required=False
    )
    view_time = TimeField(
        widget = TimeInput(),
        label='관람시간',
        required=False
    )
    

class AllReviewSortForm(Form):
    title = CharField(
        widget = TextInput( attrs={'placeholder': '제목'}),
        label='제목',
        required=False
    )
    cast = CharField(
        widget = TextInput( attrs={'placeholder': '배우 이름'}),
        label='배우',
        required=False
    )
    view_date = DateField( 
        widget = DateInput(),
        label='관람일', 
        required=False
    )
    view_time = TimeField(
        widget = TimeInput(),
        label='관람시간',
        required=False
    )

review/views.py
from django.shortcuts import render, redirect, get_object_or_404
import os
import requests
from bs4 import BeautifulSoup
from .models import Review
from .forms import NewReviewForm, ReviewSortForm, AllReviewSortForm
from django.utils import timezone
from django.core.paginator import Paginator
from django.db.models import Q
import datetime
# Create your views here.
from django.contrib.auth.models import User


def index(request):
  page = request.GET.get('page')
  if page is not None:
    showList= showListApi(page)
  else:
    page = "1"
    showList= showListApi(page)
  return render(request, 'reviewindex.html', {'showList':showList, 'page':page})


#choicefield용
# def detail(request, id):
#   mt20id = id
#   showDetail = showDetailApi(mt20id)
#   smallForm = SortSmallForm()
#   newForm = NewReviewForm()
#   if request.method == 'POST': 
#     smallForm = SortSmallForm(request.POST)
#     if smallForm.is_valid():
#       cast = smallForm.cleaned_data['cast']
#       view_date = smallForm.cleaned_data['view_date']
#       view_time = smallForm.cleaned_data['view_time']

#       reviews = Review.objects.filter(mt20id=mt20id)
#       if cast != "":
#         reviews = reviews & Review.objects.filter(Q(cast1__icontains=cast) | Q(cast2__icontains=cast))
#       if view_date != "":
#         view_date = datetime.datetime.strptime(view_date, '%Y-%m-%d')
#         reviews = reviews & Review.objects.filter(view_date = view_date)
#       if view_time != "":
#         view_time = datetime.datetime.strptime(view_time, '%H:%M:%S')
#         reviews = reviews & Review.objects.filter(view_time = view_time)
#       print(reviews)
#   else:
#     reviews = Review.objects.filter(mt20id=mt20id)
#   return render(request, 'showdetail.html', {'showDetail':showDetail, 'newForm':newForm, 'reviews':reviews, 'sortSmallForm':smallForm})


def detail(request, id):
  mt20id = id
  showDetail = showDetailApi(mt20id)
  newForm = NewReviewForm()
  sortForm = ReviewSortForm()
  ratingAvg = ratingAverage(id)
  if request.method == 'POST': 
    sortForm = ReviewSortForm(request.POST)
    if sortForm.is_valid():
      cast = sortForm.cleaned_data['cast']
      view_date = sortForm.cleaned_data['view_date']
      view_time = sortForm.cleaned_data['view_time']
    # cast = request.POST.get('cast')
    # view_date = request.POST.get('date')
    # view_time = request.POST.get('time')

      reviews = Review.objects.filter(mt20id=mt20id)
      if cast != "":
        reviews = reviews & Review.objects.filter(Q(cast1__icontains=cast) | Q(cast2__icontains=cast))
      if view_date != "" and view_date is not None:
        view_date = datetime.datetime.strftime(view_date, '%Y-%m-%d')
        reviews = reviews & Review.objects.filter(view_date = view_date)
      if view_time != "" and view_time is not None:
        view_time = datetime.time.strftime(view_time, '%H:%M')
        reviews = reviews & Review.objects.filter(view_time = view_time)
  else:
    reviews = Review.objects.filter(mt20id=mt20id)
  return render(request, 'showdetail.html', {'showDetail':showDetail, 'newForm':newForm, 'reviews':reviews, 'sortForm':sortForm, 'ratingAvg':ratingAvg})


def showListApi(page):
  open_api_key = os.environ.get('OPEN_API_KEY')
  # cpage = request.GET.get('cpage')
  # stdate = request.GET.get('stdate').replace("-", "")
  # eddate = request.GET.get('eddate').replace("-", "")

  # params = '&rows=5'+'&stdate='+stdate+'&eddate='+eddate+'&cpage='+cpage 
  params = '&stdate=20180101&eddate=20210830&shcate=AAAB&rows=6&cpage='+page
  xmlUrl = 'http://www.kopis.or.kr/openApi/restful/pblprfr?service='+open_api_key+params

  response = requests.get(xmlUrl)
  soup = BeautifulSoup(response.content, 'html.parser')

  data = soup.find_all('db')

  showList = []

  for item in data:
      show = { 'mt20id' : item.find('mt20id').get_text(), 
              'prfnm' : item.find('prfnm').get_text(),
              'prfstate' : item.find('prfstate').get_text(),
              'prfpdfrom' : item.find('prfpdfrom').get_text(),
              'prfpdto' : item.find('prfpdto').get_text(),
              'fcltynm' : item.find('fcltynm').get_text(),
              'poster' : item.find('poster').get_text(),
              'genrenm' : item.find('genrenm').get_text()}
      showList.append(show)
  return showList

def showDetailApi(mt20id):
  open_api_key = os.environ.get('OPEN_API_KEY')
  params = mt20id
  xmlUrl = 'http://www.kopis.or.kr/openApi/restful/pblprfr/'+params+'?service='+open_api_key
  response = requests.get(xmlUrl)
  soup = BeautifulSoup(response.content, 'html.parser')

  data = soup.find_all('db')

  for item in data:
      showDetail = { 'mt20id' : item.find('mt20id').get_text(), 
              'prfnm' : item.find('prfnm').get_text(),
              'prfstate' : item.find('prfstate').get_text(),
              'prfpdfrom' : item.find('prfpdfrom').get_text(),
              'prfpdto' : item.find('prfpdto').get_text(),
              'fcltynm' : item.find('fcltynm').get_text(),
              'poster' : item.find('poster').get_text(),
              'genrenm' : item.find('genrenm').get_text(),
              'prfcast' : item.find('prfcast').get_text(),
              'prfcrew' : item.find('prfcrew').get_text(),
              'prfruntime' : item.find('prfruntime').get_text(),
              'prfage' : item.find('prfage').get_text(),
              'entrpsnm' : item.find('entrpsnm').get_text(),
              'pcseguidance' : item.find('pcseguidance').get_text(),
              'sty' : item.find('sty').get_text(),
              'dtguidance' : item.find('dtguidance').get_text(),
              }
  return showDetail


def new(request, mt20id):
  if request.method == 'POST': 
    form = NewReviewForm(request.POST, request.FILES)
    title = request.POST.get('prfnm')
    if form.is_valid():
      new_review = form.save(commit=False)
      new_review.upload_date = timezone.now()
      new_review.author = request.user
      new_review.mt20id = mt20id
      new_review.title = title
      new_review.save()
      return redirect('review:detail', mt20id)
    return redirect('review:index')


def delete(request, mt20id, id):
  if request.method == 'GET':
    delete_review = Review.objects.get(id = id)
    delete_review.delete()
    return redirect('review:detail', mt20id)

# def allReviews(request):
#   if request.method == 'POST': 
#     sortForm = SortReviewForm(request.POST)

#     if sortForm.is_valid():
#       cast = sortForm.cleaned_data['cast']
#       view_date = sortForm.cleaned_data['view_date']
#       view_time = sortForm.cleaned_data['view_time']
#       title = sortForm.cleaned_data['title']

#       reviewAll = Review.objects.all()
#       if title != "":
#         reviewAll = Review.objects.filter(title = title)
#       if cast != "":
#         reviewAll = reviewAll & Review.objects.filter(Q(cast1__icontains=cast) | Q(cast2__icontains=cast))
#       if view_date != "":
#         view_date = datetime.datetime.strptime(view_date, '%Y-%m-%d')
#         reviewAll = reviewAll & Review.objects.filter(view_date = view_date)
#       if view_time != "":
#         view_time = datetime.datetime.strptime(view_time, '%H:%M:%S')
#         reviewAll = reviewAll & Review.objects.filter(view_time = view_time)

#   else:
#     reviewAll = Review.objects.all()
#     sortForm = SortReviewForm()
#   return render(request, 'allreviews.html', {'reviewAll':reviewAll, 'sortForm':sortForm})


def allReviews(request):
  allSortForm = AllReviewSortForm()
  if request.method == 'POST':
    # title = request.POST.get('title')
    # cast = request.POST.get('cast')
    # view_date = request.POST.get('date')
    # view_time = request.POST.get('time')
    allSortForm = AllReviewSortForm(request.POST)
    if allSortForm.is_valid():
      cast = allSortForm.cleaned_data['cast']
      view_date = allSortForm.cleaned_data['view_date']
      view_time = allSortForm.cleaned_data['view_time']
      title = allSortForm.cleaned_data['title']

      reviewAll = Review.objects.all()
      if title != "":
        reviewAll = Review.objects.filter(Q(title__icontains=title))
      if cast != "":
        reviewAll = reviewAll & Review.objects.filter(Q(cast1__icontains=cast) | Q(cast2__icontains=cast))
      if view_date != ""and view_date is not None:
        view_date = datetime.datetime.strftime(view_date, '%Y-%m-%d')
        reviewAll = reviewAll & Review.objects.filter(view_date = view_date)
      if view_time != ""and view_time is not None:
        view_time = datetime.time.strftime(view_time, '%H:%M')
        reviewAll = reviewAll & Review.objects.filter(view_time = view_time)
        
      paginator = Paginator(reviewAll, 6)
      page = request.GET.get('page')
      posts = paginator.get_page(page)
  else:
    reviewAll = Review.objects.all()
    paginator = Paginator(reviewAll, 6)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
  return render(request, 'allreviews.html', {'reviewAll':reviewAll, 'allSortForm': allSortForm, 'posts':posts})

def showSearch(request):
  page = request.GET.get('page')
  title = request.GET.get('title')
  # print('검색어', title)
  if page is not None:
    showList= showSearchApi(title, page)
  else:
    page = "1"
    showList= showSearchApi(title, page)
  return render(request, 'reviewindex.html', {'showList':showList, 'page':page, 'title': title})


def showSearchApi(title, page):
  # shprfnm
  open_api_key = os.environ.get('OPEN_API_KEY')
  # cpage = request.GET.get('cpage')
  # stdate = request.GET.get('stdate').replace("-", "")
  # eddate = request.GET.get('eddate').replace("-", "")

  # params = '&rows=5'+'&stdate='+stdate+'&eddate='+eddate+'&cpage='+cpage 
  params = '&stdate=20180101&eddate=20210830&rows=6&shcate=AAAB&cpage='+page+"&shprfnm="+title
  xmlUrl = 'http://www.kopis.or.kr/openApi/restful/pblprfr?service='+open_api_key+params

  response = requests.get(xmlUrl)
  soup = BeautifulSoup(response.content, 'html.parser')

  data = soup.find_all('db')

  showList = []

review/templates/allreviews.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<head>
    <style>
        .form-group {
            display: inline-block;
        }
        /* table, tr, td, div, a {
            border: 1px solid black;
        } */
        .review-table {
            display: inline-block;
            width: 80%;
            text-align: left;
            background-color: white;
            color: black;
            margin: 5 auto;
            padding: 10px;
        }
        .yellow-button {
            background-color: #F1EB73;
            /* border: #F1EB73 5px solid ; */
            padding: 5px;
        }
        .gray-text {
            color: gray;
        }
        .blue-text {
            color:dodgerblue;
        }
        .div_form {
            padding: 20px;
        }
        .div_allreview {
            padding: 20px;
        }
        .direction a, span{
            text-decoration: none;
            color:white;
        }
        .direction a:hover{
            background-color: yellowgreen;
        }
    </style>
</head>

<div class="div_form">
    <form action="" method="POST">
        {%csrf_token%}
        {{allSortForm | crispy}}
        <button type="reset" class="yellow-button">초기화</button>
        <button type="submit" class="yellow-button">검색</button>
    </form>
</div>

<div class="div_allreview">
    {%for review in posts %}
    <table class="review-table">
        <tr>
            <td style="text-align: center;width:50px;">&#127915;</td>
            <td colspan="2">{{review.title}}</td>
        </tr>
        <tr>
            <td style="text-align: center;width:50px;">&#128100;</td>
            <td style="width:80px;">{{review.author}}</td>
        </tr>
        <tr>
            <td></td>
            <td class="blue-text">만족도&nbsp;</td>
            <td class="gray-text">{{review.rating}}점</td>
        </tr>
        <tr>
            <td></td>
            <td class="blue-text">관람일시</td>
            <td class="gray-text">{{review.view_date | date:"Y-m-d"}}&nbsp;{{review.view_time}}</td>
        </tr>
        <tr>
            <td></td>
            <td class="blue-text">배우</td>
            <td class="gray-text">{{review.cast1}}&nbsp;{{review.cast2}}</td>
        </tr>
        <tr>
            <td></td>
            <td colspan="3">{{review.body}}
        </tr>
    </table>
    {%empty%}
        <br><span>검색 결과가 없습니다.</span><br>
    {%endfor%}
</div>

<div class="direction">
    {% if posts.has_previous %}
        <a href="?page=1">처음</a>
        <a href="?page={{posts.previous_page_number}}">◀</a>
    {% endif %}

        <span>{{posts.number}}</span>
        <span>of</span>
        <span>{{posts.paginator.num_pages}}</span>
    
    {% if posts.has_next %}
        <a href="?page={{posts.next_page_number}}">▶</a>
        <a href="?page={{posts.paginator.num_pages}}">끝</a>
    {% endif %}
</div>
<br><br>
{%endblock%}

review/templates/reviewindex.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/bootstrap.css">
    <script src="js/jquery-3.1.1.js"></script>
    <script src="js/bootstrap.js"></script>
    <style>
        /* table, tr, td, div, a {
            border: 1px solid black;
        } */
        tr, td {
            padding: 5px;
        }
        #id_search_title{
            width: 50vw;
        }
        .search_form {
            padding: 20px;
        }
        img {
            height: 150px;
            width: 100px;
        }
        .allreview-box a{
            color: black;
            background-color: #F1EB73;
            padding: 5px;
            margin: 10px;
            text-decoration:none;
        }
        .allreview-box a:hover{
            text-decoration: underline;
        }
        .direction {
            background-color:#F1EB73;
        }
        .direction a, span{
            text-decoration: none;
            color:black;
        }
        .direction a:hover{
            background-color: white;
        }
        .showname {
            color: black;
        }
        .showstate {
            background-color:rgb(174, 226, 243);
            color: rgb(29, 126, 216);
            width: fit-content;
            padding: 2px;
        }
        .gray_text{
            color: gray;
        }
        #id_start_date, #id_end_date {
            width: 150px;
            margin: 10px;
        }
        @media screen and (min-width: 768px) { 
            .item-box:nth-child(1){grid-column: 1;}
            .item-box:nth-child(2){ grid-column: 2;}
            .item-box:nth-child(3){grid-column: 1; grid-row: 2;}
            .item-box:nth-child(4){grid-column: 2; grid-row: 2;}
            .item-box:nth-child(5){grid-column: 1; grid-row: 3;}
            .item-box:nth-child(6){grid-column: 2; grid-row: 3;}
            .show-table_box {
                background-color: white;
                display: grid;
                grid-template-columns: 1fr 1fr;
                grid-template-rows: 1fr 1fr 1fr;
                gap: 10px 10px;
                padding: 20px;
            }
        }
        .div_poster, .div_info {
            padding: 5px;
            display: inline-block;
            text-align: left;
        }
        .item-box {
            display: inline-flex;
            justify-content: left;
        }
        .show-table_box{
            background-color: white;
            text-align: left;
            padding: 10px;
        }
    </style>
</head>


<div class="search_form">
    <form action="{%url 'review:search' %}" method="GET">
        <!-- <label for="id_start_date">검색 범위&nbsp;</label><input type="date" name="start_date" id="id_start_date"> -->
        <!-- ~<input type="date" name="end_date" id="id_end_date"> -->
        <input type="search" name="title" placeholder="찾고싶은 뮤지컬의 제목을 입력하세요" id="id_search_title">
        <button type="submit">검색</button>
    </form>
</div>

<div class="showList-wrapper">
    <div class="show-table_box">
        {% for show in showList %}
        <div class="item-box">
            <div class="div_poster"><img src="{{show.poster}}"></div>
            <div class="div_info">
                <p class="showstate">{{show.prfstate}}</p>
                <a href="{%url 'review:detail' show.mt20id %}" class="showname">{{show.prfnm}}</a>
                <p class="gray_text">{{show.genrenm}}</p>
                <p class="gray_text">{{show.prfpdfrom}}~{{show.prfpdto}}</p>
            </div>
        </div>
        {%endfor%}
    </div>

    <div class="direction">
        <a href="?page=1&title={{title}}" class="a-button">처음</a>
        {% if page != '1' %}
        <a href="?page={{page|add:'-1'}}&title={{title}}">◀</a>
        {% endif %}

        <!-- 현재 페이지 -->
        <span>{{page}}</span>
        
        <a href="?page={{page|add:'1'}}&title={{title}}">▶</a>
    </div>
</div>

<br>

<div class="allreview-box">
    <a href="{%url 'review:allreviews'%}" id="id_allreview">후기 모아보기</a>
</div>
<br>
<br>
{%endblock%}