messenger/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "messenger"

urlpatterns = [
    path('detail_m/<str:id>', detail_m, name = "detail_m"),
    path('new_m/', new_m, name = "new_m"),
    path('send_m/', send_m, name = "send_m"),
    path('received_m/', receive_m, name = "received_m"),
    path('delete_m/<str:id>', delete_m, name = "delete_m"),
    path('new/<str:receiver>', new_static, name="new_static")
]

muse/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from review.views import index

urlpatterns = [
    path('', index, name="index"),
    path('admin/', admin.site.urls),
    path('review/', include('review.urls')),
    path('ticket/', include('ticket.urls')),
    path('messenger/', include('messenger.urls')),
    path('accounts/', include('allauth.urls')),
    path('user/', include('user.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messenger/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Message(models.Model):
    sender = models.ForeignKey(get_user_model(), on_delete = models.CASCADE, related_name = "sender", default = "")
    receiver = models.ForeignKey(get_user_model(), on_delete = models.CASCADE, related_name = "receiver", default = "")
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField()
    body = models.TextField()

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

ticket/models.py
from django.db import models
from django.contrib.auth import get_user_model
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

# Create your models here.

class Ticket(models.Model):
    ticket = models.CharField(max_length=200)
    writer = models.CharField(max_length=100)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='author', null=True)
    date = models.DateTimeField()
    contents = models.TextField()
    image = models.ImageField(upload_to='ticket/', blank=True, null=True)
    image_thumbnail = ImageSpecField(source = 'image', processors = [ResizeToFill(250, 230)])

    def __str__(self):
        return self.ticket    
    
    def summary(self):
        return self.contents[:30]

messenger/forms.py
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['receiver','title','body']


class StaticReceiverForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['title','body']

messenger/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import message
from django.utils import timezone
from .models import Message
from .views import *
from .forms import MessageForm, StaticReceiverForm
from django.contrib.auth import get_user_model
# Create your views here.

def receive_m(request):
    chats = Message.objects.filter(receiver = request.user)
    return render(request, 'm_received.html', {'chats':chats})

def send_m(request):
    chats = Message.objects.filter(sender = request.user)
    return render(request, 'm_send.html', {'chats':chats})

def detail_m(request, id):
    chat = get_object_or_404(Message, pk = id)
    return render(request, 'm_detail.html', {'chat':chat})

def new_m(request):
    if request.method == 'POST':
        chatform = MessageForm(request.POST, request.FILES)
        if chatform.is_valid():
            chat = chatform.save(commit = False)
            chat.pub_date = timezone.now()
            chat.sender = request.user
            chat.save()
        return redirect('messenger:detail_m', chat.id)
    else:
        chatform = MessageForm()
        return render(request, 'm_new.html', {'chatform':chatform})

def delete_m(request, id):
    delete_message = Message.objects.get(id = id)
    delete_message.delete()
    return redirect('messenger:received_m')

def new_static(request, receiver):
    if request.method == 'POST':
        chatform = StaticReceiverForm(request.POST, request.FILES)
        if chatform.is_valid():
            chat = chatform.save(commit = False)
            chat.pub_date = timezone.now()
            chat.receiver = get_user_model().objects.get(username=receiver)
            chat.sender = request.user
            chat.save()
        return redirect('messenger:detail_m', chat.id)
    else:
        chatform = StaticReceiverForm()
        return render(request, 'm_newstatic.html', {'chatform':chatform, 'receiver':receiver})

messenger/templates/m_detail.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <Style>
        body {
            font-family: 'Alfa Slab One', 'Do Hyeon';
            color: white;
        }
        hr {
            margin: 3px;
        }
        .allreview-box a{
            color: black;
            background-color: #F1EB73;
            padding: 5px;
            margin: 10px;
            text-decoration:none;
        }
        .allreview-box a:hover{
            text-decoration: underline;
        }
        .detail-box {
            min-height: 300px;
            background-color: rgb(237, 253, 220);
            color: black;
            text-align: left;
            padding: 10px;
            margin: 10px auto;
        }
        #id_date{
            text-align: right;
        }
        .title-div{
            margin-top: 10px;
            margin-bottom: 10px;
            background-color: rgba(136, 248, 8, 0.466);
        }
        .row-name {
            width: 100px;
        }
        .btn-yellow {
            background-color: #F1EB73;
            color: black;
            text-decoration: none;
            padding: 5px;
            margin:10px;
        }
    </Style>
</head>
<!-- <br>
<h1>{{chat.title}}</h1>
<div>
보낸 사람: {{chat.sender}}
<br>
날짜: {{chat.pub_date}}
</div>
<hr>
<p><a href="{%url 'messenger:new_static' chat.sender %}">&#9992;보낸 사람에게 답장하기</a></p>
<p>{{chat.body}}</p> -->



<div class="detail-box">
    <table style="width: 100%;">
        <tr>
            <td class="row-name">&#128238;&nbsp;보낸 사람 :</td>
            <td>{{chat.sender}}</td>
        </tr>
        <tr>
            <td class="row-name">&#128233;&nbsp;받은 사람 :</td>
            <td>{{chat.receiver}}</td>
        </tr>
        <tr class="title-div">
            <td class="row-name">&#128681;&nbsp;제목 :</td>
            <td>{{chat.title}}</td>
        </tr>
        <tr>
            <td></td>
            <td id="id_date">{{chat.pub_date}}</td>
        </tr>
    </table>
    <hr>
    <p>{{chat.body | linebreaks}}</p>
</div>


<div style="margin: 20px;"><a href="{%url 'messenger:new_static' chat.sender %}" class="btn-yellow">&#9992;보낸 사람에게 답장하기</a></div>
<a href="{%url 'messenger:new_m'%}" class="btn-yellow">새 쪽지 보내기</a>
<a href="{% url 'messenger:delete_m' chat.id %}" class="btn-yellow">삭제하기</a>

{% endblock %}

messenger/templates/m_new.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        form {
            max-width: 100%;
        }
        #id_body {
            max-width: 100%;
        }
    </style>
</head>

<br>
<h1>새로운 메세지를 작성해보세요!</h1>
<br>
<br>
<form action="{%url 'messenger:new_m'%}" method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    {{chatform.as_p}}
    <br>
    <button type="submit">보내기</button>
</form>
<br><br>
{% endblock %}

messenger/templates/m_newstatic.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        form {
            max-width: 100%;
        }
        #id_body {
            max-width: 100%;
        }
    </style>
</head>
<br>
<h1>새로운 메세지를 작성해보세요!</h1>
<br>
<br>
<form action="{%url 'messenger:new_static' receiver%}" method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    <p style="font-size: large;">receiver: {{receiver}}</p>
    {{chatform.as_p}}
    <br>
    <button type="submit">보내기</button>
</form>
<br><br>
{% endblock %}

messenger/templates/m_received.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/bootstrap.css">
    <script src="js/jquery-3.1.1.js"></script>
    <script src="js/bootstrap.js"></script>
    <style>
        .receive-box {
            background-color: white;
        }
        .yellow-active:hover {
            background-color: rgba(248, 223, 81, 0.541);
        }
        .yellow-active a {
            text-decoration: none;
        }
        .yellow-active a:hover {
            text-decoration: underline;
        }
        .yellow_tr {
            background-color:rgba(248, 223, 81, 0.253);
        }
    </style>
</head>
<br>
<h1>새로운 메세지를 확인해보세요!</h1>

<div class="receive-box">
    <table class="table table-condensed">
        <tr class="yellow_tr">
            <td>보낸 사람</td>
            <td>제목</td>
            <td>날짜</td>
        </tr>
        {% for chat in chats %}
        <tr class="yellow-active">
            <td>{{chat.sender}}</td>
            <td><a href = "{%url 'messenger:detail_m' chat.id %}">{{chat.title}}</a></td>
            <td>{{chat.pub_date}}</td>
        </tr>
        {% endfor %}
    </table>
</div>


<!-- {% for chat in chats %}
<div>
<h3>{{chat.title}}</h3>
{{chat.id}}
{{chat.sender}}
{{chat.summary}} <a href = "{%url 'messenger:detail_m' chat.id %}">...더 보기</a>
<br>
<br>
</div>
{% endfor %} -->
{% endblock %}

messenger/templates/m_send.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/bootstrap.css">
    <script src="js/jquery-3.1.1.js"></script>
    <script src="js/bootstrap.js"></script>
    <style>
        .send-box {
            background-color: white;
        }
        .blue-active:hover {
            background-color: rgba(81, 195, 248, 0.432);
        }
        .blue-active a {
            text-decoration: none;
        }
        .blue-active a:hover {
            text-decoration: underline;
        }
        .blue_tr {
            background-color: rgba(106, 204, 250, 0.151);
        }
    </style>
</head>
<br>
<h1>보낸 메세지를 확인해보세요!</h1>

<div class="send-box">
    <table class="table table-condensed">
        <tr class="blue_tr">
            <td>받은 사람</td>
            <td>제목</td>
            <td>날짜</td>
        </tr>
        {% for chat in chats %}
        <tr class="blue-active">
            <td>{{chat.receiver}}</td>
            <td><a href = "{%url 'messenger:detail_m' chat.id %}">{{chat.title}}</a></td>
            <td>{{chat.pub_date}}</td>
        </tr>
        {% endfor %}
    </table>
</div>


<!-- {% for chat in chats %}
<div>
<h3>{{chat.title}}</h3>
{{chat.id}}
{{chat.sender}}
{{chat.summary}} <a href = "{%url 'messenger:detail_m' chat.id %}">...더 보기</a>
<br>
<br>
</div>
{% endfor %} -->
{% endblock %}